tag: spleen_segformer_2d
network:
  - type: segformer  # Name of the network
    config: # Configuration of the network
      loss_function: cross_entropy
      learning_rate: 0.5
      epochs: 100
      print_every: 100
dataset: # List of datasets
  - type: MSD  # Name of the dataset (same used in the --dataset option)
    config: # Configuration of the dataset
      path: data/MSD/Task09_Spleen